<a href="https://colab.research.google.com/github/akhilanil-369/Machine-Learning/blob/main/naive_bayes_lung_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/lung_cancer_examples.csv")
df

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [ ]:
df.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [ ]:
df.tail()

Name   Surname  Age  Smokes  AreaQ  Alkhol  Result
54    Ernest   Borgnine   26      13      6       1       0
55      Alec   Guinness   77      20      5       4       1
56  Charlton     Heston   75      15      3       5       1
57   Gregory       Peck   43      30      3       8       1
58    Sidney    Poitier   51      25      9       0       0

In [ ]:
df.dtypes

Name       object
Surname    object
Age         int64
Smokes      int64
AreaQ       int64
Alkhol      int64
Result      int64
dtype: object

In [ ]:
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [ ]:
#Encoding
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["Name"] = lb.fit_transform(df["Name"])
df["Name"]

0     27
1     27
2      5
3      1
4     10
5      8
6     35
7     30
8     36
9     40
10    15
11    48
12    26
13    23
14     2
15    29
16    29
17     3
18    32
19    17
20    24
21    34
22    18
23    46
24    41
25    31
26    38
27    44
28    28
29    16
30    33
31    22
32    22
33    39
34    42
35    11
36    21
37    43
38    12
39    14
40     9
41    24
42    45
43    47
44    25
45    19
46    20
47    37
48     6
49    29
50    29
51     4
52    32
53    17
54    13
55     0
56     7
57    18
58    46
Name: Name, dtype: int64

In [ ]:
df["Surname"]=lb.fit_transform(df["Surname"])
df["Surname"]

0     47
1      7
2      0
3     44
4     28
5     36
6     43
7      1
8     24
9     31
10    29
11     5
12     8
13    48
14    27
15    19
16    19
17    42
18    39
19    22
20    14
21    37
22    34
23    35
24    17
25    30
26    38
27    41
28    46
29    16
30     4
31    26
32    32
33    13
34     9
35    21
36    18
37    11
38     6
39    10
40    23
41    14
42    12
43    40
44    25
45    33
46     2
47    24
48    45
49    19
50    19
51    42
52    39
53    22
54     3
55    15
56    20
57    34
58    35
Name: Surname, dtype: int64

In [ ]:
x=df.iloc[:,:-1].values
x

array([[27, 47, 35,  3,  5,  4],
       [27,  7, 27, 20,  2,  5],
       [ 5,  0, 30,  0,  5,  2],
       [ 1, 44, 28,  0,  8,  1],
       [10, 28, 68,  4,  5,  6],
       [ 8, 36, 34,  0, 10,  0],
       [35, 43, 58, 15, 10,  0],
       [30,  1, 22, 12,  5,  2],
       [36, 24, 45,  2,  6,  0],
       [40, 31, 52, 18,  4,  5],
       [15, 29, 33,  4,  8,  0],
       [48,  5, 18, 10,  6,  3],
       [26,  8, 25,  2,  5,  1],
       [23, 48, 28, 20,  2,  8],
       [ 2, 27, 34, 25,  4,  8],
       [29, 19, 39, 18,  8,  1],
       [29, 19, 42, 22,  3,  5],
       [ 3, 42, 19, 12,  8,  0],
       [32, 39, 62,  5,  4,  3],
       [17, 22, 73, 10,  7,  6],
       [24, 14, 55, 15,  1,  3],
       [34, 37, 33,  8,  8,  1],
       [18, 34, 22, 20,  6,  2],
       [46, 35, 44,  5,  8,  1],
       [41, 17, 77,  3,  2,  6],
       [31, 30, 21, 20,  5,  3],
       [38, 38, 37, 15,  6,  2],
       [44, 41, 34, 12,  8,  0],
       [28, 46, 55, 20,  1,  4],
       [16, 16, 40, 20,  2,  7],
       [33

In [ ]:
y=df.iloc[:,-1].values
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [ ]:
x.ndim

2

In [ ]:
y.ndim

1

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
x_train

array([[ 2, 27, 34, 25,  4,  8],
       [22, 32, 47, 15,  1,  8],
       [29, 19, 62, 20,  5,  6],
       [16, 16, 40, 20,  2,  7],
       [43, 11, 62, 15,  5,  5],
       [ 7, 20, 75, 15,  3,  5],
       [32, 39, 62,  5,  4,  3],
       [ 0, 15, 77, 20,  5,  4],
       [44, 41, 34, 12,  8,  0],
       [29, 19, 39, 18,  8,  1],
       [ 8, 36, 34,  0, 10,  0],
       [22, 26, 56, 20,  3,  3],
       [29, 19, 42, 22,  3,  5],
       [29, 19, 42, 12,  6,  2],
       [24, 14, 55, 15,  1,  3],
       [ 4, 42, 44, 30,  1,  6],
       [36, 24, 45,  2,  6,  0],
       [23, 48, 28, 20,  2,  8],
       [31, 30, 21, 20,  5,  3],
       [ 3, 42, 19, 12,  8,  0],
       [46, 35, 51, 25,  9,  0],
       [18, 34, 43, 30,  3,  8],
       [32, 39, 26, 34,  1,  8],
       [12,  6, 33, 25,  8,  2],
       [27,  7, 27, 20,  2,  5],
       [26,  8, 25,  2,  5,  1],
       [19, 33, 21, 20,  8,  3],
       [41, 17, 77,  3,  2,  6],
       [35, 43, 58, 15, 10,  0],
       [46, 35, 44,  5,  8,  1],
       [21

In [ ]:
x_test

array([[38, 38, 37, 15,  6,  2],
       [11, 21, 25, 20,  8,  2],
       [47, 40, 63, 20,  4,  5],
       [28, 46, 55, 20,  1,  4],
       [48,  5, 18, 10,  6,  3],
       [ 5,  0, 30,  0,  5,  2],
       [42,  9, 26, 10,  7,  2],
       [20,  2, 31, 20,  9,  4],
       [ 9, 23, 50, 20,  2,  4],
       [18, 34, 22, 20,  6,  2],
       [10, 28, 68,  4,  5,  6],
       [15, 29, 33,  4,  8,  0],
       [33,  4, 36, 13,  5,  2],
       [24, 14, 47, 12,  8,  0],
       [39, 13, 62, 25,  3,  4],
       [45, 12, 69, 20,  5,  4],
       [ 6, 45, 53, 20,  6,  3],
       [30,  1, 22, 12,  5,  2]])

In [ ]:
#Noramalization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [ ]:
x_train

array([[-1.71669954,  0.05616921, -0.5753424 ,  1.17164345, -0.41605821,
         1.74855353],
       [-0.15085569,  0.46740808,  0.24459744, -0.02629624, -1.57913003,
         1.74855353],
       [ 0.39718966, -0.60181298,  1.19068187,  0.57267361, -0.02836761,
         0.98588656],
       [-0.62060884, -0.84855631, -0.19690863,  0.57267361, -1.19143942,
         1.36722005],
       [ 1.49328036, -1.25979518,  1.19068187, -0.02629624, -0.02836761,
         0.60455308],
       [-1.32523858, -0.51956521,  2.01062171, -0.02629624, -0.80374882,
         0.60455308],
       [ 0.63206624,  1.04314251,  1.19068187, -1.22423593, -0.41605821,
        -0.15811388],
       [-1.87328393, -0.93080408,  2.1367663 ,  0.57267361, -0.02836761,
         0.2232196 ],
       [ 1.57157255,  1.20763806, -0.5753424 , -0.38567814,  1.13470421,
        -1.30211433],
       [ 0.39718966, -0.60181298, -0.25998093,  0.33308567,  1.13470421,
        -0.92078085],
       [-1.24694639,  0.79639918, -0.5753424 , -1.

In [ ]:
x_test

array([[ 0.83027809,  1.16229234, -0.27140133,  0.04072045,  0.24253563,
        -0.54232614],
       [-1.03784761,  0.05085029, -0.99513823,  0.77368849,  1.21267813,
        -0.54232614],
       [ 1.45298665,  1.29305023,  1.29669527,  0.77368849, -0.72760688,
         1.41004798],
       [ 0.13837968,  1.68532389,  0.814204  ,  0.77368849, -2.18282063,
         0.7592566 ],
       [ 1.52217649, -0.99521282, -1.41731808, -0.6922476 ,  0.24253563,
         0.10846523],
       [-1.45298665, -1.32210754, -0.69358119, -2.15818369, -0.24253563,
        -0.54232614],
       [ 1.10703745, -0.73369704, -0.93482682, -0.6922476 ,  0.72760688,
        -0.54232614],
       [-0.41513904, -1.19134965, -0.63326978,  0.77368849,  1.69774938,
         0.7592566 ],
       [-1.17622729,  0.18160818,  0.51264697,  0.77368849, -1.69774938,
         0.7592566 ],
       [-0.55351872,  0.90077656, -1.17607245,  0.77368849,  0.24253563,
        -0.54232614],
       [-1.10703745,  0.5085029 ,  1.5982523 , -1.

In [ ]:
from sklearn.naive_bayes import BernoulliNB
base=BernoulliNB() #creating variable
base.fit(x_train,y_train) #the data teaching to machine
y_pred=base.predict(x_test) #the machine predicts value according to the model
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
print(cm)

[[10  0]
 [ 1  7]]


In [ ]:
score=accuracy_score(y_test,y_pred)
score

0.9444444444444444